""" Afficher du texte avec la fonction print() """

print("Hello World !")
print('Hello World !')
print("""   Afficher un long texte ...
            Afficher un long texte ...
            Afficher un long texte ...
            Afficher un long texte ...
            Afficher un long texte ...
            Afficher un long texte ...""")
